language: objective-c
osx_image: xcode8
branches:
  only:
    - master
env:
- LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
before_install:
- gem install xcpretty -N
script:
- xcodebuild -project Spread.xcodeproj -scheme "Spread" -sdk iphonesimulator
  -destination "platform=iOS Simulator,name=iPhone 7" ONLY_ACTIVE_ARCH=NO test
